[local]
localhost ansible_connection=local

; [ios_router]
; router-core ansible_host =

; [ios_switches]
; l3-sw ansible_host=192.168.1.1
; ; l2-sw-1 ansible_host = 
; ; l2-sw-2 ansible_host =

; [ios_switches:vars]
; ansible_network_os=cisco.ios.ios
; ansible_connection=network_cli
; ansible_user=admin
; ansible_password=admin123
; ansible_become=yes
; ansible_become_method=enable 