; [local]
; localhost ansible_connection=local

[router]
router ansible_host =
[router:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_user=
ansible_password=
ansible_become=yes
ansible_become_method=enable


[L3_switch]
l3-sw ansible_host=192.168.1.1
[L3_switch:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_user=admin
ansible_password=admin123
ansible_become=yes
ansible_become_method=enable

[SW1]
sw1 ansible_host=
[SW1:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_user=
ansible_password=
ansible_become=yes
ansible_become_method=enable

[SW2]
l2-sw-2 ansible_host =
[SW2:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_user=
ansible_password=
ansible_become=yes
ansible_become_method=enable
