[all:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_user=admin
ansible_password=admin123
ansible_become=yes
ansible_become_method=enable
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[router]
r1 ansible_host=192.168.1.5

[L3_switch]
l3-sw ansible_host=192.168.1.1

[SW1]
sw1 ansible_host=192.168.1.3

[SW2]
l2-sw-2 ansible_host=192.168.1.4